apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-proxy
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  #ingressClassName: ingress-appgw-deployment
  rules:
    - host: example.com
      http:
        paths:
          - backend: 
              service:
                name: opentelemetry-demo-frontendproxy
                port: 
                  number: 8080

            path: "/"
            pathType: Prefix